home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home")
]

mosque/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls")),
    path("", include("about.urls")),
    path("", include("contact.urls")),
    path("", include("topic.urls")),
    path("", include("donation.urls")),
    path("", include("footer_apps.urls")),
]

home/models.py
from django.db import models


class Community(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=80)

    read = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "Communities"

    def __str__(self):
        return f"Name: {self.name}, Read: {self.read}"


class Home(models.Model):
    title = models.CharField(max_length=100)
    quote = models.CharField(max_length=220)
    quote_author = models.CharField(max_length=100)

    testimonial = models.CharField(max_length=1000)
    testimonial_role = models.CharField(max_length=100)
    testimonial_name = models.CharField(max_length=100)
    testimonial_country = models.CharField(
        max_length=100, null=True, blank=True)

    def __str__(self):
        return self.title

topic/models.py
from django.db import models
from datetime import date

TOPIC_CHOICES = (
    ("Normal", "Normal"),
    ("Main", "Main"),
)


class Topic(models.Model):
    small_title = models.CharField(
        max_length=80, default="THIS SHOULD BE A SHORT TITLE")

    small_desc = models.TextField(
        max_length=100, default="THIS SHOULD BE A SHORT DESCRIPTION")

    topic_type = models.CharField(
        choices=TOPIC_CHOICES, max_length=100, default=TOPIC_CHOICES[0])

    def __str__(self):
        return self.small_title


class Author(models.Model):
    topic = models.ForeignKey(Topic, on_delete=None)
    profile = models.ImageField(upload_to="profile_img")
    name = models.CharField(max_length=160)
    status = models.CharField(max_length=100, default="speaker")
    facebook = models.URLField(max_length=950, blank=True)
    twitter = models.URLField(max_length=950, blank=True)
    slug = models.SlugField(default="Change-me", max_length=300)
    email = models.EmailField(max_length=300)

    def __str__(self):
        return self.name


class Chapter(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)

    title = models.CharField(max_length=200)

    desc = models.TextField(max_length=700)

    video = models.FileField(upload_to="topic_files")
    pub_date = models.DateField(default=date.today)
    thumbnail = models.ImageField(upload_to="thumbnails")

    def __str__(self):
        return f"Chapter: {self.title}"

home/forms.py
from django import forms
from .models import Community


class CommunityForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-name c-forms', "placeholder": "Enter Name..."}), label='')

    email = forms.CharField(widget=forms.EmailInput
                            (attrs={'class': 'form-email c-forms',
                                    "placeholder": "Enter Email..."
                                    }), label='')

    class Meta:
        model = Community
        fields = ("name", "email")

home/views.py
from django.shortcuts import render, redirect
from .forms import CommunityForm
from .models import Home
from topic.models import Topic, Chapter


def home(request):
    if request.method == "POST":
        community = CommunityForm(request.POST)

        if community.is_valid():
            community.save()

            return redirect("home")

    else:
        community = CommunityForm()

    home_object = Home.objects.first()
    # Getting the first topic object with a certain type
    topic1 = Topic.objects.filter(topic_type="Main")[0]
    topic2 = Topic.objects.filter(topic_type="Main")[1]
    topic3 = Topic.objects.filter(topic_type="Main")[2]
    # Getting 4 chapter objects which is ordered by publish date first
    latest = Chapter.objects.all().order_by("-pub_date")[0: 5]

    context = {
        "community": community,
        "home": home_object,
        "topic1": topic1,
        "topic2": topic2,
        "topic3": topic3,
        "latest": latest
    }

    return render(request, "home/home.htm", context)

templates/home/home.htm
{% extends 'base.htm' %} {% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  {% block head %}
  <title>Home | Be Part Of Our Islamic Community And Learn More Of Our Religion</title>
  <link rel="stylesheet" href="{% static 'home/style.css' %}" />

  <meta name="description"
    content="We give valuable information and knowledge all about islam and many other religion." />
  <meta name="keywords" content="Islamic, islamic education, islamic home, home, islamic aid, educational, charity" />
  {% endblock %}
</head>

<body>
  {% block content %}
  <div class="container">
    <div class="s1">
      <img src="{% static 'home/imgs/new_home.jpg' %}" alt="Mosque" class="cover" />

      <h1>Gateway To Knowledge</h1>
      <p>"{{ home.quote }}" - <small> {{ home.quote_author }}</small></p>

      <a href="#scroll" class="drop-a"><img src="{% static 'home/imgs/drop.svg' %}" alt="Drop" class="drop" /></a>
    </div>

    <div class="s2">
      <h2>Watch Our Latest Episodes</h2>
      <p class="accent slogan">The human mind is our fundamental resource</p>

      <div class="topic-container">
        {% for new in latest %}
        <div class="topic">
          <a href="{% url 'chapter-detail' new.id%}">
            <p class="topic-name accent">
              {{ new.title }}
            </p>
          </a>
          <p class="author">{{new.author}}</p>
        </div>
        {% endfor %}
        <!-- <div class="topic">
            <p class="topic-name accent">
              This is the max charachter it should be
            </p>
            <p class="author">Author</p>
          </div>

          <div class="topic">
            <p class="topic-name accent">
              This is the max charachter it should be
            </p>
            <p class="author">Author</p>
          </div>

          <div class="topic">
            <p class="topic-name accent">
              This is the max charachter it should be
            </p>
            <p class="author">Author</p>
          </div> -->
      </div>
    </div>

    <div class="s3" id="scroll">
      <h2>Hot Topics</h2>
      <p class="slogan accent">The human mind is our fundamental resource</p>

      <div class="boxes">
        <div class="box b1">
          <div class="details">
            <div class="number">
              <h4>01</h4>
            </div>

            <h3>{{ topic1.small_title|title }}</h3>
            <p class="box-desc">
              {{ topic1.small_desc }}
            </p>

            <hr />
          </div>

          {% for author in topic1.author_set.all %}
          <img src="{{ author.profile.url }}" alt="Topic-Img" style="width: 110px; height: 218px; object-fit: cover;" />
          {% endfor %}
        </div>

        <div class="box b2">
          <div class="details">
            <div class="number">
              <h4>02</h4>
            </div>

            <h3>{{ topic2.small_title|title }}</h3>
            <p class="box-desc">
              {{ topic2.small_desc }}
            </p>

            <hr />
          </div>
          {% for author in topic2.author_set.all %}
          <img src="{{ author.profile.url }}" alt="Topic-Img" />
          {% endfor %}
        </div>

        <div class="box b3">
          <div class="details">
            <div class="number">
              <h4>03</h4>
            </div>

            <h3>{{ topic3.small_title|title }}</h3>
            <p class="box-desc">
              {{ topic3.small_desc }}
            </p>

            <hr />
          </div>
          {% for author in topic3.author_set.all %}
          <img src="{{ author.profile.url }}" alt="Topic-Img" style="width: 110px; height: 218px; object-fit: cover;" />
          {% endfor %}
        </div>
      </div>

      <a href="{% url 'topic' %}"><button class="more-topics btn">More Topics</button></a>
    </div>

    <div class="s4">
      <img src="{% static 'home/imgs/sky.jpg' %}" alt="Cover" class="testimonial-cover" />

      <h2>Testimonial</h2>
      <p class="slogan accent sg">
        The human mind is our fundamental resource
      </p>

      <div class="person-one">
        <p class="quote1">
          "{{ home.testimonial }}"
        </p>

        {% if home.testimonial_country %}
        <p class="author1">
          {{ home.testimonial_role }}, {{ home.testimonial_name }} -
          <small>{{ home.testimonial_country }}</small>
        </p>

        {% else %}
        <p class="author1">
          {{ home.testimonial_role }} - {{ home.testimonial_name }}
        </p>

        {% endif %}
      </div>
    </div>

    <div class="s5">
      <h2>Join The Community</h2>
      <p class="slogan accent comm-slogan">
        The human mind is our fundamental resource
      </p>
      <form method="POST">
        {% csrf_token %} {{ community }}

        <button type="submit" class="submit btn">Submit</button>
      </form>
    </div>

    <div class="s6">
      <h3 class="copyright">Copyright &copy; 2020 - name</h3>
      <h3 class="fontawesome">fontawesome Fonts</h3>
      <ul>
        <li><a href="{% url 'about' %}">About</a></li>
        <li><a href="{% url 'policy' %}" class="list-pad">Policy</a></li>
        <li><a href="{% url 'disclaimer' %}" class="list-pad">Disclaimer</a></li>
        <li><a href="" class="list-pad">FAQ</a></li>
        <li><a href="{% url 'contact' %}" class="list-pad">Contact</a></li>
      </ul>
    </div>
  </div>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/2.1.2/TimelineLite.min.js"
    integrity="sha256-5HW1hilN77unDg9wwY2mmXL1G8/hBMrYOgiB+BqsxNg=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/2.1.2/plugins/CSSPlugin.min.js"
    integrity="sha256-UJt5JHwfrhok9SvTqbi6rRw2ajY0ugeYsIT2pioVDJY=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/2.1.2/TweenLite.min.js"
    integrity="sha256-VfpswwlYKouVmlpnJW0MszMzLm9lH2yfB6ty3d1WsB4=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/3.2.0/anime.min.js"
    integrity="sha256-hBMojZuWKocCflyaG8T19KBq9OlTlK39CTxb8AUWKhY=" crossorigin="anonymous"></script>
  <script src="{% static 'home/app.js' %}"></script>
  {% endblock %}
</body>

</html>