home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home")
]

mosque/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls")),
    path("", include("about.urls")),
    path("", include("contact.urls")),
    path("", include("topic.urls")),
    path("", include("donation.urls")),
    path("", include("footer_apps.urls")),
]

topic/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("topic/", views.TopicListView.as_view(), name="topic"),
    path("speaker/", views.SpeakerView.as_view(), name="speaker"),
    path("speaker/<str:slug>", views.SpeakerDetailView.as_view(),
         name="speaker-detail"),
    path("chapter/<int:pk>", views.ChapterDetailView.as_view(),
         name="chapter-detail")
]

topic/models.py
from django.db import models
from datetime import date

TOPIC_CHOICES = (
    ("Normal", "Normal"),
    ("Main", "Main"),
)


class Topic(models.Model):
    small_title = models.CharField(
        max_length=80, default="THIS SHOULD BE A SHORT TITLE")

    small_desc = models.TextField(
        max_length=100, default="THIS SHOULD BE A SHORT DESCRIPTION")

    topic_type = models.CharField(
        choices=TOPIC_CHOICES, max_length=100, default=TOPIC_CHOICES[0])

    def __str__(self):
        return self.small_title


class Author(models.Model):
    topic = models.ForeignKey(Topic, on_delete=None)
    profile = models.ImageField(upload_to="profile_img")
    name = models.CharField(max_length=160)
    status = models.CharField(max_length=100, default="speaker")
    facebook = models.URLField(max_length=950, blank=True)
    twitter = models.URLField(max_length=950, blank=True)
    slug = models.SlugField(default="Change-me", max_length=300)
    email = models.EmailField(max_length=300)

    def __str__(self):
        return self.name


class Chapter(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)

    title = models.CharField(max_length=200)

    desc = models.TextField(max_length=700)

    video = models.FileField(upload_to="topic_files")
    pub_date = models.DateField(default=date.today)
    thumbnail = models.ImageField(upload_to="thumbnails")

    def __str__(self):
        return f"Chapter: {self.title}"

topic/views.py
from django.shortcuts import render
from .models import Topic, Chapter, Author
from django.views.generic import ListView, DetailView
from .filters import TopicFilter


class TopicListView(ListView):
    template_name = "topic/topic.htm"
    model = Topic
    context_object_name = "topics"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["filter"] = TopicFilter(
            self.request.GET, queryset=self.get_queryset())
        return context  # Creating the filter by getting the queryset's title


class SpeakerView(ListView):
    template_name = "topic/speaker.htm"
    paginate_by = 6
    model = Author
    context_object_name = "speakers"


class SpeakerDetailView(DetailView):  # Sort of both a DetailView and ListView
    template_name = "topic/speaker_detail.htm"
    model = Author
    context_object_name = "speaker"


class ChapterDetailView(DetailView):
    template_name = "topic/chapter_detail.htm"
    model = Chapter
    context_object_name = "chapter"

templates/topic/chapter_detail.htm
{% extends 'base.htm' %} {% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  {% block head %}
  <title>Chapter | Stay Educated Through Our Website</title>
  <link rel="stylesheet" href="{% static 'chapter_detail/style.css' %}" />

  <meta name="description"
    content="Make sure to stay educated on islam to know the true meaning of this beutiful religion." />
  <meta name="keywords" content="Islamic, islamic education, islamic chapters, chapters, islamic aid, educational " />
  {% endblock %}
</head>

<body>
  {% block content %}
  <div class="container">
    <div class="s1">
      <video poster="{{ chapter.thumbnail.url }}" controls src="{{ chapter.video.url }}" width="100"></video>

      <h3 class="title">{{ chapter.title|title }}</h3>

      <div class="side-info">
        <p class="name">{{ chapter.author.name }}</p>
        <p class="date">{{ chapter.pub_date }}</p>
      </div>

      <hr class="line line1" />
      <p class="desc">{{ chapter.desc }}</p>
      <hr class="line line2" />
    </div>

    <div class="s6">
      <h3 class="copyright">Copyright &copy; 2020 - name</h3>
      <h3 class="fontawesome">fontawesome Fonts</h3>
      <ul>
        <li><a href="{% url 'about' %}">About</a></li>
        <li><a href="{% url 'policy' %}" class="list-pad">Policy</a></li>
        <li><a href="{% url 'disclaimer' %}" class="list-pad">Disclaimer</a></li>
        <li><a href="" class="list-pad">FAQ</a></li>
        <li><a href="{% url 'contact' %}" class="list-pad">Contact</a></li>
      </ul>
    </div>
  </div>

  <script src="{% static 'chapter_detail/app.js' %}"></script>
  {% endblock %}
</body>

</html>

templates/topic/speaker.htm
{% extends 'base.htm' %} {% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  {% block head %}
  <title>Speakers | Search For Well-Known Speakers</title>
  <link rel="stylesheet" href="{% static 'speaker/style.css' %}" />

  <meta name="description"
    content="Here we have many speakers who are well known or upcoming. Listen to them and show your support by following their social media." />
  <meta name="keywords"
    content="Islamic, islamic education, islamic speakers, speakers, islamic aid, educational, islamic channel" />
  {% endblock %}
</head>

<body>
  {% block content %}
  <div class="containers">
    <div class="s1">
      <h2>Browse Through Our Podcasts</h2>
      <p>Visit speakers and go through new content.</p>
    </div>
    <div class="s2">
      <div class="s2-container">
        {% for speaker in speakers %}
        <div class="item">
          <div class="back">
            <a href="{% url 'speaker-detail' speaker.slug%} "><img src="{{ speaker.profile.url }}"
                alt="Profile Picture" /></a>
          </div>

          <h5 class="name">{{ speaker.name|title }}</h5>
        </div>
        {% endfor %}
      </div>
      <div class="pagination">
        {% if is_paginated %} {% if page_obj.has_previous %}
        <div class="border">
          <a class="btn btn-outline-info mb-4" href="?page=1">
            << </a>
        </div>
        <div class="border">
          <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">
            < </a>
        </div>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
        <div class="border current">
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        </div>
        {% elif num > page_obj.number|add:'-3' and num <
              page_obj.number|add:'3' %}
        <div class="border">
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        </div>
        {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
        <div class="border">
          <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">>
          </a>
        </div>
        <div class="border">
          <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">>>
          </a>
        </div>
        {% endif %} {% endif %}
      </div>
    </div>

    <div class="s6">
      <h3 class="copyright">Copyright &copy; 2020 - name</h3>
      <h3 class="fontawesome">fontawesome Fonts</h3>
      <ul>
        <li><a href="{% url 'about' %}">About</a></li>
        <li><a href="{% url 'policy' %}" class="list-pad">Policy</a></li>
        <li><a href="{% url 'disclaimer' %}" class="list-pad">Disclaimer</a></li>
        <li><a href="" class="list-pad">FAQ</a></li>
        <li><a href="{% url 'contact' %}" class="list-pad">Contact</a></li>
      </ul>
    </div>
  </div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/2.1.2/TimelineLite.min.js"
    integrity="sha256-5HW1hilN77unDg9wwY2mmXL1G8/hBMrYOgiB+BqsxNg=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/2.1.2/plugins/CSSPlugin.min.js"
    integrity="sha256-UJt5JHwfrhok9SvTqbi6rRw2ajY0ugeYsIT2pioVDJY=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/2.1.2/TweenLite.min.js"
    integrity="sha256-VfpswwlYKouVmlpnJW0MszMzLm9lH2yfB6ty3d1WsB4=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/3.2.0/anime.min.js"
    integrity="sha256-hBMojZuWKocCflyaG8T19KBq9OlTlK39CTxb8AUWKhY=" crossorigin="anonymous"></script>
  <script src="{% static 'speaker/app.js' %}"></script>
  {% endblock %}
</body>

</html>

templates/topic/speaker_detail.htm
{% extends 'base.htm' %} {% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  {% block head %}
  <title>Speakers</title>
  <link rel="stylesheet" href="{% static 'speaker_detail/style.css' %}" />

  <meta name="description" content="Watch new chapters from speakers." />
  <meta name="keywords" content="Islamic, islamic education, islamic topics, topics, islamic aid, educational, " />
  {% endblock %}
</head>

<body>
  {% block content %}
  <div class="containers">
    <div class="s1">
      <h2>Visit Your Favourite Speakers</h2>
      <p>
        Support your favourite speakers by following them on their social media
      </p>
    </div>

    <div class="s2">
      <div class="author">
        <div class="author-details">
          <img src="{{ speaker.profile.url }}" alt="Author" class="author-img">

          <img src="{% static 'speaker_detail/imgs/arrow_right.svg' %}" alt="Arrow" class="arrow-right">
          <div class="info">
            <h2 class="topic-name">{{ speaker.topic.small_title }}</h2>
            <p class="topic-desc">{{ speaker.topic.small_desc }}</p>
          </div>
          <p class="author-name">{{ speaker.name }}</p>
        </div>

        <aside class="author-social">
          <div class="inner-social">
            <img src="{% static 'speaker_detail/imgs/arrow_left.svg' %}" alt="Arrow" class="arrow-left">

            <fieldset>Sidebar</fieldset>

            <div class="social">
              <a href="{{ speaker.facebook }}" target="_blank"><img
                  src="{% static 'speaker_detail/imgs/facebook.svg' %}" alt="Facebook" class="facebook icons"></a>
              <a href="{{ speaker.twitter }}" target="_blank"><img src="{% static 'speaker_detail/imgs/twitter.svg' %}"
                  alt="Twitter" class="twitter icons"></a>
              <a href="mailto:{{ speaker.email }}" target="_blank"><img
                  src="{% static 'speaker_detail/imgs/email.svg' %}" alt="Email" class="email icons"></a>
            </div>

            <p class="their_email">Email - {{ speaker.email }}</p>
            <p class="phone"></p>

            <p class="support">Show your support to these creators by visiting their social medias and thanking them.
            </p>
          </div>
        </aside>
      </div>

      <div class="s3">
        {% for chapter in speaker.topic.chapter_set.all %}
        <div class="chapter-container">
          <h3 class="chapter">{{ chapter|title }}</h3>
          <p class="date">{{ chapter.pub_date }}</p>
          <a href="{% url 'chapter-detail' chapter.id %}"><button class="visit btn">Visit</button></a>
        </div>
        {% endfor %}
      </div>

      <div class="s6">
        <h3 class="copyright">Copyright &copy; 2020 - name</h3>
        <h3 class="fontawesome">fontawesome Fonts</h3>
        <ul>
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'policy' %}" class="list-pad">Policy</a></li>
          <li><a href="{% url 'disclaimer' %}" class="list-pad">Disclaimer</a></li>
          <li><a href="" class="list-pad">FAQ</a></li>
          <li><a href="{% url 'contact' %}" class="list-pad">Contact</a></li>
        </ul>
      </div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/2.1.2/TimelineLite.min.js"
      integrity="sha256-5HW1hilN77unDg9wwY2mmXL1G8/hBMrYOgiB+BqsxNg=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/2.1.2/plugins/CSSPlugin.min.js"
      integrity="sha256-UJt5JHwfrhok9SvTqbi6rRw2ajY0ugeYsIT2pioVDJY=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/2.1.2/TweenLite.min.js"
      integrity="sha256-VfpswwlYKouVmlpnJW0MszMzLm9lH2yfB6ty3d1WsB4=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/3.2.0/anime.min.js"
      integrity="sha256-hBMojZuWKocCflyaG8T19KBq9OlTlK39CTxb8AUWKhY=" crossorigin="anonymous"></script>
    <script src="{% static 'speaker_detail/app.js' %}"></script>
    {% endblock %}
</body>

</html>

templates/topic/topic.htm
{% extends 'base.htm' %} {% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  {% block head %}
  <title>Topic | All The Religous Topics</title>
  <link rel="stylesheet" href="{% static 'topic/style.css' %}" />

  <meta name="description"
    content="Visit our topic section with hundreds of islamic quotes and speakers to listen from. Download these resources to always listen to on your phone or free time." />
  <meta name="keywords" content="Islamic, islamic education, islamic topics, topics, islamic aid, educational, " />
  {% endblock %}
</head>

<body>
  {% block content %}
  <div class="container">
    <div class="s1">
      <h2>Browse Through Our Topics</h2>
      <p>
        Watch hundreds of chapters all related to a topic
      </p>

      <div class="form-container">
        <form method="GET">
          {% csrf_token %}
          <div class="form">
            {{ filter.form }}

            <button type="submit" class="submit">
              <img src="{% static 'topic/imgs/mag.svg' %}" alt="mag" class="mag" />
            </button>
          </div>
        </form>
      </div>
      <!-- Search -->
    </div>

    <div class="s2">
      <div class="whole-object-container">
        {% for topic in filter.qs %}
        <div class="topic-container">
          <div class="title-container">
            <img src="{% static 'topic/imgs/carpet.svg' %}" alt="Carpet" class="carpet" />
            <h3 class="title">{{ topic.small_title }}</h3>
          </div>

          <div class="slider">
            <div class="content-container">
              <ul>
                {% for chapters in topic.chapter_set.all %}
                <li>
                  <a href="{% url 'chapter-detail' chapters.id %}">{{ chapters }}</a>
                </li>
                {% endfor %}
              </ul>
            </div>
          </div>

          {% endfor %}
        </div>
      </div>
    </div>
  </div>
  <div class="s6">
    <h3 class="copyright">Copyright &copy; 2020 - name</h3>
    <h3 class="fontawesome">fontawesome Fonts</h3>
    <ul>
      <li><a href="{% url 'about' %}">About</a></li>
      <li><a href="{% url 'policy' %}" class="list-pad">Policy</a></li>
      <li><a href="{% url 'disclaimer' %}" class="list-pad">Disclaimer</a></li>
      <li><a href="" class="list-pad">FAQ</a></li>
      <li><a href="{% url 'contact' %}" class="list-pad">Contact</a></li>
    </ul>
  </div>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/2.1.2/TimelineLite.min.js"
    integrity="sha256-5HW1hilN77unDg9wwY2mmXL1G8/hBMrYOgiB+BqsxNg=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/2.1.2/plugins/CSSPlugin.min.js"
    integrity="sha256-UJt5JHwfrhok9SvTqbi6rRw2ajY0ugeYsIT2pioVDJY=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/2.1.2/TweenLite.min.js"
    integrity="sha256-VfpswwlYKouVmlpnJW0MszMzLm9lH2yfB6ty3d1WsB4=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/3.2.0/anime.min.js"
    integrity="sha256-hBMojZuWKocCflyaG8T19KBq9OlTlK39CTxb8AUWKhY=" crossorigin="anonymous"></script>
  <script src="{% static 'topic/app.js' %}"></script>
  {% endblock %}
</body>

</html>